### ISSUE TITLE
Skyux data-entry grid does not support vertical scrollbar for rows

### ISSUE THREAD

**Issue by mohitvashisht88** [blackbaud/skyux-ag-grid#36]
Hi 

I am not sure how to have vertical scroll bar within grid other than having it on parent container.
I don't want it on parent because it scrolls headers too, which I think should be freezed as in normal ag-grid or skyux list grid

I tried setting  it by just giving height to ag-grid-angular but it breaks if I am setting gridOptions  using SkyAgGridService.
this.gridOptions = this.skyAgGridService.getGridOptions({ gridOptions: this.gridOptions });

**And it works perfectly  if I am not using SkyAgGridService, but then I would not be able to have skyux css.**

Please let me know if I am missing anything, I just need vertical scrollbar with column headers freezed, same as in normal agrid.

Also let me know if you need more information, I can provide you the screenshots.
Thanks!

**Comment by Blackbaud-ErikaMcVey** [comment]
SKY UX data entry grid is ag-grid, so there isn't anything you can do in ag-grid that you cannot do using ag-grid with the SKY service. The SKY service simply adds styling, some cell editors and renderers for your convenience, and the default grid settings we expect to be the most used.

The reason you're seeing different scrollbar behavior with and without the service is because one of the default settings we set is `domLayout: 'autoHeight'`. If you set `domLayout` to `'normal'` in the `gridOptions` you pass to `this.skyAgGridService.getGridOptions()` then you should see the column headers freeze.

Unfortunately, the `'normal'` layout does not work perfectly with SKY infinite scroll. To fix this we are styling the headers to be sticky regardless of the `domLayout` setting. This change is currently in review, and will be out in version 3.0.0 of sky-ag-grid.

**Comment by mohitvashisht88** [comment]
Thanks for the information, I think as headers will be sticky in version 3.0.0 of sky-ag-grid,
similarly might be we need horizontal scrollbar handling if still we go with design having scroll with parent container. Currently horizontal scroll bar moves to the end, and if user need to horizontally scroll he needs to load all data else its keep on going down.
